apiVersion: v1
kind: Secret
metadata:
  name: acr-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJrbmF1bWVua29jb250YWluZXJyZWdpc3RyeS5henVyZWNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAia25hdW1lbmtvQ29udGFpbmVyUmVnaXN0cnkiLAogICAgICAicGFzc3dvcmQiOiAia2hNM3BWVmRQVnVaNW5WcHc4ZjZHTFdjb0FnVXhsemRMV2p3UG1pdFV2K0FDUkFPblpZciIsCiAgICAgICJlbWFpbCI6ICJraXIubmF1bWVua29AZ21haWwuY29tIiwKICAgICAgImF1dGgiOiAiYmFzZTY0X2VuY29kZWRfYXV0aCIKICAgIH0KICB9Cn0=
