apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    tier: database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        tier: database
    spec:
      containers:
      - name: database
        image: mcr.microsoft.com/azure-sql-edge
        ports:
        - containerPort: 1433
        imagePullPolicy: Always
        # volumeMounts:
        # - name: database-init-volume
        #   mountPath: /script
        # command: ["/script/database-init.sh"]
        env:
        - name: SA_PASSWORD
          value: "@someThingComplicated1234"
        - name: ACCEPT_EULA
          value: "Y"
      # volumes:
      # - name: database-init-volume
      #   configMap:
      #     name: database-init
      #     defaultMode: 0744
