apiVersion: v1
kind: ConfigMap
metadata:
  name: database-init
data:
  database-init.sh: |
    #!/bin/bash
    ls
    cd ../Web/
    dotnet restore
    dotnet tool restore
    dotnet ef database update -c catalogcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj
    dotnet ef database update -c appidentitydbcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj
