apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: knaumenkocontainerregistry.azurecr.io/web:latest
      ports:
      - containerPort: 8080
      imagePullPolicy: Always
  imagePullSecrets:
    - name: acr-credentials