apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 30080
  type: LoadBalancer